services:
  nextjs:
    container_name: nextjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - nextjs
networks:
  nextjs:
    driver: bridge